server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # No permitir almacenamiento en caché para env-config.js
    location = /env-config.js {
        alias /shared/env-config.js;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
        default_type application/javascript;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Deshabilitar logs ruidosos para favicon
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
}
